import { describe, expect, it } from "vitest";
import { computeConfigurationRows } from "./rows-query";

describe("computeConfigurationRows", () => {
  it("filters by namespace, query and sort direction", () => {
    const rows = [
      {
        uid: "a",
        name: "cfg-a",
        namespace: "default",
        problemScore: 20,
        keys: 1,
        labels: "",
        globalDefault: false,
        type: "configmap",
        handler: "",
        holder: "",
        webhooks: 0,
        status: "ok",
        minAvailable: "-",
        maxUnavailable: "-",
        currentHealthy: 0,
        desiredHealthy: 0,
        metrics: 0,
        minPods: 0,
        maxPods: 0,
        replicas: "-",
        bindings: "-",
        resource: "-",
        group: "-",
        version: "-",
        scope: "-",
        kind: "-",
        controller: "-",
        apiGroup: "-",
        externalIP: "-",
        selector: "-",
        endpoints: "-",
        loadBalancers: "-",
        policyTypes: "-",
        storageClass: "-",
        size: "-",
        pods: "-",
        capacity: "-",
        value: "-",
        resourceVersion: "1",
        serviceType: "-",
        clusterIP: "-",
        ports: "-",
        phase: "-",
        storage: "-",
        claim: "-",
        provisioner: "-",
        reclaimPolicy: "-",
        isDefaultStorageClass: false,
        createdAt: "2024-01-01T00:00:00.000Z",
        details: "alpha",
        driftDetected: false,
      },
      {
        uid: "b",
        name: "cfg-b",
        namespace: "ops",
        problemScore: 80,
        keys: 1,
        labels: "",
        globalDefault: false,
        type: "configmap",
        handler: "",
        holder: "",
        webhooks: 0,
        status: "ok",
        minAvailable: "-",
        maxUnavailable: "-",
        currentHealthy: 0,
        desiredHealthy: 0,
        metrics: 0,
        minPods: 0,
        maxPods: 0,
        replicas: "-",
        bindings: "-",
        resource: "-",
        group: "-",
        version: "-",
        scope: "-",
        kind: "-",
        controller: "-",
        apiGroup: "-",
        externalIP: "-",
        selector: "-",
        endpoints: "-",
        loadBalancers: "-",
        policyTypes: "-",
        storageClass: "-",
        size: "-",
        pods: "-",
        capacity: "-",
        value: "-",
        resourceVersion: "2",
        serviceType: "-",
        clusterIP: "-",
        ports: "-",
        phase: "-",
        storage: "-",
        claim: "-",
        provisioner: "-",
        reclaimPolicy: "-",
        isDefaultStorageClass: false,
        createdAt: "2024-01-01T00:00:00.000Z",
        details: "beta",
        driftDetected: false,
      },
    ];

    const filtered = computeConfigurationRows(rows, {
      selectedNamespaces: ["default", "ops"],
      search: "cfg",
      quickFilter: "all",
      sortBy: "problemScore",
      sortDirection: "desc",
    });

    expect(filtered).toHaveLength(2);
    expect(filtered[0]?.name).toBe("cfg-b");
  });
});
