import type { PageData } from "$entities/cluster";

export type WorkloadComponentModule = { default: unknown };
export type WorkloadComponentLoader = () => Promise<WorkloadComponentModule>;

export const workloadComponentLoaders: Record<string, WorkloadComponentLoader> = {
  overview: () => import("$widgets/datalists/ui/overview.svelte"),
  globaltriage: () => import("$widgets/datalists/ui/triage/global-triage-panel.svelte"),
  pods: () => import("$widgets/datalists/ui/pods-list/pods-list.svelte"),
  deployments: () => import("$widgets/datalists/ui/deployments-list.svelte"),
  daemonsets: () => import("$widgets/datalists/ui/daemon-sets-list.svelte"),
  statefulsets: () => import("$widgets/datalists/ui/stateful-sets-list.svelte"),
  replicasets: () => import("$widgets/datalists/ui/replica-sets-list.svelte"),
  replicationcontrollers: () => import("$widgets/datalists/ui/replication-controllers-list.svelte"),
  jobs: () => import("$widgets/datalists/ui/jobs-list.svelte"),
  cronjobs: () => import("$widgets/datalists/ui/cron-jobs-list.svelte"),
  cronjobshealth: () => import("$widgets/datalists/ui/cronjobs-health/cronjobs-health-list.svelte"),
  podsrestarts: () => import("$widgets/datalists/ui/pods-restarts/pods-restarts-list.svelte"),
  deprecationscan: () =>
    import("$widgets/datalists/ui/cluster-health/deprecation-scan-panel.svelte"),
  versionaudit: () => import("$widgets/datalists/ui/cluster-health/version-audit-panel.svelte"),
  backupaudit: () => import("$widgets/datalists/ui/cluster-health/backup-audit-panel.svelte"),
  helm: () => import("$widgets/datalists/ui/cluster-health/helm-panel.svelte"),
  helmcatalog: () => import("$widgets/datalists/ui/cluster-health/helm-catalog-panel.svelte"),
  alertshub: () => import("$widgets/datalists/ui/cluster-health/alerts-hub-panel.svelte"),
  armorhub: () => import("$widgets/datalists/ui/cluster-health/armor-hub-panel.svelte"),
  metricssources: () => import("$widgets/datalists/ui/cluster-health/metrics-sources-panel.svelte"),
  compliancehub: () => import("$widgets/datalists/ui/cluster-health/compliance-hub-panel.svelte"),
  trivyhub: () => import("$widgets/datalists/ui/cluster-health/trivy-hub-panel.svelte"),
  rotatecerts: () => import("$widgets/datalists/ui/cluster-health/rotate-certs-panel.svelte"),
  gitopsbootstrap: () =>
    import("$widgets/datalists/ui/cluster-health/gitops-bootstrap-panel.svelte"),
  capacityintelligence: () =>
    import("$widgets/datalists/ui/cluster-health/capacity-intelligence-panel.svelte"),
  performanceobs: () => import("$widgets/datalists/ui/cluster-health/performance-panel.svelte"),
  securityaudit: () => import("$widgets/datalists/ui/cluster-health/security-audit-panel.svelte"),
  authsecurity: () => import("$widgets/datalists/ui/cluster-health/auth-security-panel.svelte"),
  plugins: () => import("$widgets/datalists/ui/cluster-health/plugin-marketplace-panel.svelte"),
  visualizer: () => import("$widgets/datalists/ui/cluster-health/workload-visualizer-panel.svelte"),
  resourcemap: () => import("$widgets/datalists/ui/cluster-health/resource-map-panel.svelte"),
  nodespressures: () => import("$widgets/datalists/ui/nodes-pressures/nodes-pressures-list.svelte"),
  nodesstatus: () => import("$widgets/datalists/ui/nodes-list/nodes-statuses-list.svelte"),
  namespaces: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  configmaps: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  secrets: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  resourcequotas: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  limitranges: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  horizontalpodautoscalers: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  poddisruptionbudgets: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  priorityclasses: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  runtimeclasses: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  leases: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  mutatingwebhookconfigurations: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  validatingwebhookconfigurations: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  serviceaccounts: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  roles: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  rolebindings: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  clusterroles: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  clusterrolebindings: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  accessreviews: () => import("$widgets/datalists/ui/access-control/access-reviews-panel.svelte"),
  customresourcedefinitions: () =>
    import("$widgets/datalists/ui/custom-resources/custom-resources-list.svelte"),
  services: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  endpoints: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  endpointslices: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  ingresses: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  ingressclasses: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  gatewayclasses: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  gateways: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  httproutes: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  referencegrants: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  portforwarding: () => import("$widgets/datalists/ui/network/port-forwarding-panel.svelte"),
  networkpolicies: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  persistentvolumeclaims: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  persistentvolumes: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  storageclasses: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  volumeattributesclasses: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  volumesnapshots: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  volumesnapshotcontents: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  volumesnapshotclasses: () => import("$widgets/datalists/ui/configuration-list.svelte"),
  csistoragecapacities: () => import("$widgets/datalists/ui/configuration-list.svelte"),
};

export function createWorkloadProps(
  workloadType: string | null,
  data: PageData,
  workloadData: unknown,
) {
  if (!workloadType) {
    return data;
  }

  const propsMap = {
    overview: { ...data, overview: workloadData },
    globaltriage: { ...data },
    pods: { ...data },
    deployments: { ...data, deployments: workloadData },
    daemonsets: { ...data, daemonsets: workloadData },
    statefulsets: { ...data, statefulsets: workloadData },
    replicasets: { ...data, replicasets: workloadData },
    replicationcontrollers: { ...data, replicationcontrollers: workloadData },
    jobs: { ...data, jobs: workloadData },
    cronjobs: { ...data, cronjobs: workloadData },
    cronjobshealth: { ...data },
    podsrestarts: { ...data },
    deprecationscan: { ...data },
    versionaudit: { ...data },
    backupaudit: { ...data },
    helm: { ...data },
    helmcatalog: { ...data },
    rotatecerts: { ...data },
    gitopsbootstrap: { ...data },
    capacityintelligence: { ...data },
    performanceobs: { ...data },
    securityaudit: { ...data },
    authsecurity: { ...data },
    plugins: { ...data },
    visualizer: { ...data },
    resourcemap: { ...data },
    alertshub: { ...data },
    armorhub: { ...data },
    metricssources: { ...data },
    compliancehub: { ...data },
    trivyhub: { ...data },
    nodespressures: { ...data },
    nodesstatus: { ...data, nodes: workloadData },
    namespaces: { ...data, items: workloadData, workloadKey: "namespaces" },
    configmaps: { ...data, items: workloadData, workloadKey: "configmaps" },
    secrets: { ...data, items: workloadData, workloadKey: "secrets" },
    resourcequotas: { ...data, items: workloadData, workloadKey: "resourcequotas" },
    limitranges: { ...data, items: workloadData, workloadKey: "limitranges" },
    horizontalpodautoscalers: {
      ...data,
      items: workloadData,
      workloadKey: "horizontalpodautoscalers",
    },
    poddisruptionbudgets: { ...data, items: workloadData, workloadKey: "poddisruptionbudgets" },
    priorityclasses: { ...data, items: workloadData, workloadKey: "priorityclasses" },
    runtimeclasses: { ...data, items: workloadData, workloadKey: "runtimeclasses" },
    leases: { ...data, items: workloadData, workloadKey: "leases" },
    mutatingwebhookconfigurations: {
      ...data,
      items: workloadData,
      workloadKey: "mutatingwebhookconfigurations",
    },
    validatingwebhookconfigurations: {
      ...data,
      items: workloadData,
      workloadKey: "validatingwebhookconfigurations",
    },
    serviceaccounts: { ...data, items: workloadData, workloadKey: "serviceaccounts" },
    roles: { ...data, items: workloadData, workloadKey: "roles" },
    rolebindings: { ...data, items: workloadData, workloadKey: "rolebindings" },
    clusterroles: { ...data, items: workloadData, workloadKey: "clusterroles" },
    clusterrolebindings: { ...data, items: workloadData, workloadKey: "clusterrolebindings" },
    accessreviews: { ...data },
    customresourcedefinitions: {
      ...data,
      items: workloadData,
      workloadKey: "customresourcedefinitions",
    },
    services: { ...data, items: workloadData, workloadKey: "services" },
    endpoints: { ...data, items: workloadData, workloadKey: "endpoints" },
    endpointslices: { ...data, items: workloadData, workloadKey: "endpointslices" },
    ingresses: { ...data, items: workloadData, workloadKey: "ingresses" },
    ingressclasses: { ...data, items: workloadData, workloadKey: "ingressclasses" },
    gatewayclasses: { ...data, items: workloadData, workloadKey: "gatewayclasses" },
    gateways: { ...data, items: workloadData, workloadKey: "gateways" },
    httproutes: { ...data, items: workloadData, workloadKey: "httproutes" },
    referencegrants: { ...data, items: workloadData, workloadKey: "referencegrants" },
    portforwarding: { ...data },
    networkpolicies: { ...data, items: workloadData, workloadKey: "networkpolicies" },
    persistentvolumeclaims: { ...data, items: workloadData, workloadKey: "persistentvolumeclaims" },
    persistentvolumes: { ...data, items: workloadData, workloadKey: "persistentvolumes" },
    storageclasses: { ...data, items: workloadData, workloadKey: "storageclasses" },
    volumeattributesclasses: {
      ...data,
      items: workloadData,
      workloadKey: "volumeattributesclasses",
    },
    volumesnapshots: { ...data, items: workloadData, workloadKey: "volumesnapshots" },
    volumesnapshotcontents: {
      ...data,
      items: workloadData,
      workloadKey: "volumesnapshotcontents",
    },
    volumesnapshotclasses: {
      ...data,
      items: workloadData,
      workloadKey: "volumesnapshotclasses",
    },
    csistoragecapacities: { ...data, items: workloadData, workloadKey: "csistoragecapacities" },
  };

  if (workloadType in propsMap) {
    return propsMap[workloadType as keyof typeof propsMap];
  }
  return data;
}
