import type { WorkloadType } from "../model/workloads";

export const KUBECTL_COMMANDS: Record<WorkloadType, string> = {
  pods: "get pods ${ns}",
  deployments: "get deployments ${ns}",
  daemonsets: "get daemonsets ${ns}",
  statefulsets: "get statefulsets ${ns}",
  replicasets: "get replicasets ${ns}",
  replicationcontrollers: "get replicationcontrollers ${ns}",
  jobs: "get jobs ${ns}",
  cronjobs: "get cronjobs ${ns}",
  cronjobshealth: "get cronjobs ${ns}",
  globaltriage: "",
  overview: "",
  podsrestarts: "get pods ${ns}",
  nodesstatus: "get nodes",
  nodespressures: "get nodes",
  deprecationscan: "",
  versionaudit: "",
  backupaudit: "",
  alertshub: "",
  armorhub: "",
  metricssources: "",
  compliancehub: "",
  trivyhub: "",
  helm: "",
  helmcatalog: "",
  namespaces: "get namespaces",
  configmaps: "get configmaps ${ns}",
  secrets: "get secrets ${ns}",
  resourcequotas: "get resourcequotas ${ns}",
  limitranges: "get limitranges ${ns}",
  horizontalpodautoscalers: "get horizontalpodautoscalers ${ns}",
  poddisruptionbudgets: "get poddisruptionbudgets ${ns}",
  priorityclasses: "get priorityclasses",
  runtimeclasses: "get runtimeclasses",
  leases: "get leases ${ns}",
  mutatingwebhookconfigurations: "get mutatingwebhookconfigurations",
  validatingwebhookconfigurations: "get validatingwebhookconfigurations",
  serviceaccounts: "get serviceaccounts ${ns}",
  roles: "get roles ${ns}",
  rolebindings: "get rolebindings ${ns}",
  clusterroles: "get clusterroles",
  clusterrolebindings: "get clusterrolebindings",
  accessreviews: "",
  customresourcedefinitions: "get customresourcedefinitions",
  services: "get services ${ns}",
  endpoints: "get endpoints ${ns}",
  endpointslices: "get endpointslices ${ns}",
  ingresses: "get ingresses ${ns}",
  ingressclasses: "get ingressclasses",
  gatewayclasses: "get gatewayclasses",
  gateways: "get gateways ${ns}",
  httproutes: "get httproutes ${ns}",
  referencegrants: "get referencegrants ${ns}",
  portforwarding: "",
  networkpolicies: "get networkpolicies ${ns}",
  persistentvolumeclaims: "get persistentvolumeclaims ${ns}",
  persistentvolumes: "get persistentvolumes",
  storageclasses: "get storageclasses",
  volumeattributesclasses: "get volumeattributesclasses",
  volumesnapshots: "get volumesnapshots ${ns}",
  volumesnapshotcontents: "get volumesnapshotcontents",
  volumesnapshotclasses: "get volumesnapshotclasses",
  csistoragecapacities: "get csistoragecapacities ${ns}",
  rotatecerts: "get certificatesigningrequests",
  gitopsbootstrap: "get namespaces",
  capacityintelligence: "get nodes",
  performanceobs: "get nodes",
  securityaudit: "get clusterroles",
  authsecurity: "get serviceaccounts ${ns}",
  plugins: "get namespaces",
  visualizer: "get deployments ${ns}",
} as const;
