import type { SectionRuntimeDescriptor } from "./contracts";

export const CONFIGURATION_SECTION_WORKLOADS = [
  "namespaces",
  "configmaps",
  "secrets",
  "resourcequotas",
  "limitranges",
  "horizontalpodautoscalers",
  "poddisruptionbudgets",
  "priorityclasses",
  "runtimeclasses",
  "leases",
  "mutatingwebhookconfigurations",
  "validatingwebhookconfigurations",
] as const;

export const NETWORK_SECTION_WORKLOADS = [
  "services",
  "endpoints",
  "endpointslices",
  "ingresses",
  "ingressclasses",
  "gatewayclasses",
  "gateways",
  "httproutes",
  "referencegrants",
  "networkpolicies",
] as const;

export const STORAGE_SECTION_WORKLOADS = [
  "persistentvolumeclaims",
  "persistentvolumes",
  "storageclasses",
  "volumeattributesclasses",
  "volumesnapshots",
  "volumesnapshotcontents",
  "volumesnapshotclasses",
  "csistoragecapacities",
] as const;

export type ConfigurationSectionWorkload = (typeof CONFIGURATION_SECTION_WORKLOADS)[number];
export type NetworkSectionWorkload = (typeof NETWORK_SECTION_WORKLOADS)[number];
export type StorageSectionWorkload = (typeof STORAGE_SECTION_WORKLOADS)[number];

export const SECTION_RUNTIME_DESCRIPTORS = {
  namespaces: {
    family: "configuration",
    workloadKey: "namespaces",
    title: "Namespaces",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: true,
  },
  configmaps: {
    family: "configuration",
    workloadKey: "configmaps",
    title: "ConfigMaps",
    supportsSelection: false,
    supportsDetails: false,
    supportsWorkbench: false,
  },
  secrets: {
    family: "configuration",
    workloadKey: "secrets",
    title: "Secrets",
    supportsSelection: false,
    supportsDetails: false,
    supportsWorkbench: false,
  },
  resourcequotas: {
    family: "configuration",
    workloadKey: "resourcequotas",
    title: "Resource Quotas",
    supportsSelection: false,
    supportsDetails: false,
    supportsWorkbench: false,
  },
  limitranges: {
    family: "configuration",
    workloadKey: "limitranges",
    title: "Limit Ranges",
    supportsSelection: false,
    supportsDetails: false,
    supportsWorkbench: false,
  },
  horizontalpodautoscalers: {
    family: "configuration",
    workloadKey: "horizontalpodautoscalers",
    title: "Horizontal Pod Autoscalers",
    supportsSelection: false,
    supportsDetails: false,
    supportsWorkbench: false,
  },
  poddisruptionbudgets: {
    family: "configuration",
    workloadKey: "poddisruptionbudgets",
    title: "Pod Disruption Budgets",
    supportsSelection: false,
    supportsDetails: false,
    supportsWorkbench: false,
  },
  priorityclasses: {
    family: "configuration",
    workloadKey: "priorityclasses",
    title: "Priority Classes",
    supportsSelection: false,
    supportsDetails: false,
    supportsWorkbench: false,
  },
  runtimeclasses: {
    family: "configuration",
    workloadKey: "runtimeclasses",
    title: "Runtime Classes",
    supportsSelection: false,
    supportsDetails: false,
    supportsWorkbench: false,
  },
  leases: {
    family: "configuration",
    workloadKey: "leases",
    title: "Leases",
    supportsSelection: false,
    supportsDetails: false,
    supportsWorkbench: false,
  },
  mutatingwebhookconfigurations: {
    family: "configuration",
    workloadKey: "mutatingwebhookconfigurations",
    title: "Mutating Webhook Configurations",
    supportsSelection: false,
    supportsDetails: false,
    supportsWorkbench: false,
  },
  validatingwebhookconfigurations: {
    family: "configuration",
    workloadKey: "validatingwebhookconfigurations",
    title: "Validating Webhook Configurations",
    supportsSelection: false,
    supportsDetails: false,
    supportsWorkbench: false,
  },
  services: {
    family: "network",
    workloadKey: "services",
    title: "Services",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: true,
  },
  endpoints: {
    family: "network",
    workloadKey: "endpoints",
    title: "Endpoints",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: false,
  },
  ingresses: {
    family: "network",
    workloadKey: "ingresses",
    title: "Ingresses",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: false,
  },
  ingressclasses: {
    family: "network",
    workloadKey: "ingressclasses",
    title: "Ingress Classes",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: false,
  },
  gatewayclasses: {
    family: "network",
    workloadKey: "gatewayclasses",
    title: "Gateway Classes",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: false,
  },
  gateways: {
    family: "network",
    workloadKey: "gateways",
    title: "Gateways",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: false,
  },
  httproutes: {
    family: "network",
    workloadKey: "httproutes",
    title: "HTTP Routes",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: false,
  },
  referencegrants: {
    family: "network",
    workloadKey: "referencegrants",
    title: "Reference Grants",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: false,
  },
  networkpolicies: {
    family: "network",
    workloadKey: "networkpolicies",
    title: "Network Policies",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: false,
  },
  endpointslices: {
    family: "network",
    workloadKey: "endpointslices",
    title: "EndpointSlices",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: false,
  },
  persistentvolumeclaims: {
    family: "storage",
    workloadKey: "persistentvolumeclaims",
    title: "Persistent Volume Claims",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: true,
  },
  persistentvolumes: {
    family: "storage",
    workloadKey: "persistentvolumes",
    title: "Persistent Volumes",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: true,
  },
  storageclasses: {
    family: "storage",
    workloadKey: "storageclasses",
    title: "Storage Classes",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: true,
  },
  volumeattributesclasses: {
    family: "storage",
    workloadKey: "volumeattributesclasses",
    title: "Volume Attributes Classes",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: true,
  },
  volumesnapshots: {
    family: "storage",
    workloadKey: "volumesnapshots",
    title: "Volume Snapshots",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: true,
  },
  volumesnapshotcontents: {
    family: "storage",
    workloadKey: "volumesnapshotcontents",
    title: "Volume Snapshot Contents",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: true,
  },
  volumesnapshotclasses: {
    family: "storage",
    workloadKey: "volumesnapshotclasses",
    title: "Volume Snapshot Classes",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: true,
  },
  csistoragecapacities: {
    family: "storage",
    workloadKey: "csistoragecapacities",
    title: "CSI Storage Capacities",
    supportsSelection: true,
    supportsDetails: true,
    supportsWorkbench: true,
  },
} satisfies Record<string, SectionRuntimeDescriptor>;
